import { WorkoutDay } from "./types";

export const WORKOUT_DAYS: WorkoutDay[] = [
  {
    key: "push",
    dayIndex: 1,
    day: "MON",
    label: "Day 1",
    title: "PUSH",
    subtitle: "Upper Chest Priority",
    color: "#E63946",
    icon: "🔥",
    rpe: "7-8",
    duration: "~50 min",
    warmup: "5 min incline walk + 2 warm-up sets on first lift (50%, 70%)",
    exercises: [
      { id: "push-1", name: "Incline Bench Press", sets: "3 × 6-8", rpe: "RPE 7-8", rest: "2 min", note: "Control the eccentric 3 sec down", type: "compound" },
      { id: "push-2", name: "Seated Overhead Press (DB)", sets: "3 × 8-10", rpe: "RPE 7", rest: "90 sec", note: "Seated saves energy vs standing", type: "compound" },
      { id: "push-3a", name: "Incline DB Flyes", sets: "3 × 10-12", rpe: "RPE 7", rest: "—", note: "Superset with 3B", type: "superset-a" },
      { id: "push-3b", name: "Cable Lateral Raises", sets: "3 × 12-15", rpe: "RPE 7", rest: "60 sec", note: "Cables = constant tension, less joint fatigue", type: "superset-b" },
      { id: "push-4", name: "Rope Tricep Pushdowns", sets: "2 × 12-15", rpe: "RPE 7", rest: "60 sec", note: "2 sets — triceps already hit from pressing", type: "isolation" },
      { id: "push-5", name: "Hanging Knee Raises", sets: "2 × 12-15", rpe: "RPE 6", rest: "45 sec", note: "Core block — decompresses spine post-pressing", type: "core" },
    ],
  },
  {
    key: "pull",
    dayIndex: 2,
    day: "TUE",
    label: "Day 2",
    title: "PULL",
    subtitle: "Back Thickness & Arms",
    color: "#457B9D",
    icon: "💪",
    rpe: "7-8",
    duration: "~50 min",
    warmup: "5 min row machine + band pull-aparts × 15",
    exercises: [
      { id: "pull-1", name: "Lat Pulldown (Wide Grip)", sets: "3 × 8-10", rpe: "RPE 7-8", rest: "90 sec", note: "Full stretch at top, squeeze at bottom", type: "compound" },
      { id: "pull-2", name: "Chest-Supported T-Bar Row", sets: "3 × 8-10", rpe: "RPE 7-8", rest: "90 sec", note: "Spine-safe — saves lower back for squats tomorrow", type: "compound" },
      { id: "pull-3", name: "Straight-Arm Pulldown", sets: "3 × 12-15", rpe: "RPE 7", rest: "60 sec", note: "Adds lat volume without spinal loading", type: "isolation" },
      { id: "pull-4a", name: "Face Pulls (Rope, High)", sets: "3 × 15-20", rpe: "RPE 6", rest: "—", note: "Superset with 4B — light, prehab-level", type: "superset-a" },
      { id: "pull-4b", name: "Incline DB Hammer Curls", sets: "3 × 10-12", rpe: "RPE 7", rest: "60 sec", note: "Incline = better stretch, more growth stimulus", type: "superset-b" },
      { id: "pull-5", name: "Dead Hang + Plate Pinch", sets: "2 × 30 sec", rpe: "RPE 6", rest: "30 sec", note: "Grip & forearm work + spinal decompression", type: "core" },
    ],
  },
  {
    key: "legs-heavy",
    dayIndex: 3,
    day: "WED",
    label: "Day 3",
    title: "LEGS",
    subtitle: "Heavy Compound",
    color: "#2A9D8F",
    icon: "⚡",
    rpe: "8-9",
    duration: "~55 min",
    warmup: "5 min bike + goblet squats × 10 + leg swings",
    alert: "Take Amino Energy pre-workout",
    exercises: [
      { id: "legs1-1", name: "Back Squats", sets: "3 × 6-8", rpe: "RPE 8", rest: "2.5 min", note: "Belt up on working sets. No grinding reps.", type: "compound" },
      { id: "legs1-2", name: "Romanian Deadlifts", sets: "3 × 8-10", rpe: "RPE 7-8", rest: "2 min", note: "Hinge, don't squat. Stop at mid-shin.", type: "compound" },
      { id: "legs1-3a", name: "Leg Extensions", sets: "3 × 12-15", rpe: "RPE 7", rest: "—", note: "Superset with 3B — pause 1 sec at top", type: "superset-a" },
      { id: "legs1-3b", name: "Standing Calf Raises", sets: "3 × 12-15", rpe: "RPE 7", rest: "60 sec", note: "3 sec eccentric stretch at bottom", type: "superset-b" },
      { id: "legs1-4", name: "Pallof Press (Cable)", sets: "2 × 10/side", rpe: "RPE 6", rest: "30 sec", note: "Anti-rotation core — protects spine for heavy days", type: "core" },
    ],
  },
  {
    key: "rest-1",
    dayIndex: 4,
    day: "THU",
    label: "Day 4",
    title: "REST",
    subtitle: "Active Recovery",
    color: "#6B7280",
    icon: "🧘",
    rpe: "—",
    duration: "20-30 min optional",
    warmup: "",
    isRest: true,
    recovery: [
      "20 min walk (zone 2 cardio — fat burn, blood flow)",
      "Foam roll quads, hamstrings, lats — 5 min",
      "Stretch hip flexors & chest — 5 min",
      "Hydrate: 3-4L water throughout the day",
      "Sleep target: 7-9 hours",
      "Protein: hit 1.6-2.2g per kg bodyweight",
    ],
  },
  {
    key: "upper",
    dayIndex: 5,
    day: "FRI",
    label: "Day 5",
    title: "UPPER",
    subtitle: "Overall Mass",
    color: "#E76F51",
    icon: "🎯",
    rpe: "7-8",
    duration: "~55 min",
    warmup: "5 min row machine + 2 warm-up sets on bench (50%, 70%)",
    exercises: [
      { id: "upper-1", name: "Flat DB Bench Press", sets: "3 × 8-10", rpe: "RPE 7-8", rest: "2 min", note: "DBs for better ROM & joint health vs barbell", type: "compound" },
      { id: "upper-2", name: "Single-Arm Cable Row", sets: "3 × 10-12/arm", rpe: "RPE 7", rest: "60 sec/arm", note: "Unilateral = fixes imbalances, less spinal load", type: "compound" },
      { id: "upper-3a", name: "DB Shoulder Press", sets: "3 × 8-12", rpe: "RPE 7", rest: "—", note: "Superset with 3B", type: "superset-a" },
      { id: "upper-3b", name: "Cable Bicep Curls", sets: "3 × 10-12", rpe: "RPE 7", rest: "60 sec", note: "Constant tension > barbell curls for recovery", type: "superset-b" },
      { id: "upper-4", name: "Overhead Tricep Ext. (Cable)", sets: "2 × 12-15", rpe: "RPE 7", rest: "60 sec", note: "2 sets — triceps pre-fatigued from pressing", type: "isolation" },
      { id: "upper-5", name: "Rear Delt Cable Flyes", sets: "2 × 15-20", rpe: "RPE 6", rest: "45 sec", note: "Balances shoulder health & posture", type: "isolation" },
      { id: "upper-6", name: "Ab Wheel Rollouts", sets: "2 × 8-12", rpe: "RPE 7", rest: "45 sec", note: "Core block — anti-extension strength", type: "core" },
    ],
  },
  {
    key: "legs-machine",
    dayIndex: 6,
    day: "SAT",
    label: "Day 6",
    title: "LEGS + CORE",
    subtitle: "Machine / Unilateral",
    color: "#9B5DE5",
    icon: "⚡",
    rpe: "7",
    duration: "~50 min",
    warmup: "5 min bike + bodyweight lunges × 10/leg",
    alert: "Take Amino Energy pre-workout",
    exercises: [
      { id: "legs2-1", name: "Leg Press", sets: "3 × 10-12", rpe: "RPE 7", rest: "90 sec", note: "Feet high & wide = more glute/ham, less knee stress", type: "compound" },
      { id: "legs2-2", name: "Seated Leg Curls", sets: "3 × 10-12", rpe: "RPE 7", rest: "60 sec", note: "Slow eccentric — 3 sec negative", type: "isolation" },
      { id: "legs2-3", name: "Bulgarian Split Squats", sets: "2 × 10/leg", rpe: "RPE 7-8", rest: "60 sec/leg", note: "Hold DBs. Balance + hypertrophy in one.", type: "compound" },
      { id: "legs2-4a", name: "Cable Crunches", sets: "3 × 12-15", rpe: "RPE 7", rest: "—", note: "Superset with 4B", type: "superset-a" },
      { id: "legs2-4b", name: "Seated Calf Raises", sets: "3 × 15-20", rpe: "RPE 6", rest: "45 sec", note: "Higher reps — soleus focus", type: "superset-b" },
      { id: "legs2-5", name: "Farmer's Carry", sets: "2 × 40 sec", rpe: "RPE 7", rest: "60 sec", note: "Traps, grip, core, conditioning in one move", type: "core" },
    ],
  },
  {
    key: "rest-2",
    dayIndex: 0,
    day: "SUN",
    label: "Day 7",
    title: "REST",
    subtitle: "Full Recovery + Progress Photo",
    color: "#6B7280",
    icon: "📸",
    rpe: "—",
    duration: "Full day off",
    warmup: "",
    isRest: true,
    recovery: [
      "📸 Take your weekly progress photo (front, side, back)",
      "Full rest — no gym, no HIIT",
      "Light walk or stretching only if desired",
      "Meal prep for the week ahead",
      "Prioritize sleep: this is when muscle is BUILT",
      "Magnesium + zinc before bed (ZMA optional)",
      "Reflect: log any joint pain or unusual fatigue",
    ],
  },
];

export const PROGRESSION_RULES = [
  {
    icon: "📈",
    rule: "Top-of-Range Rule",
    detail: "Hit the top of the rep range for all sets → add 2.5 kg (upper) or 5 kg (lower) next session.",
  },
  {
    icon: "🎯",
    rule: "RPE Cap",
    detail: "Never exceed RPE 8 on compounds, RPE 7 on isolations. Leave 2-3 reps in the tank always.",
  },
  {
    icon: "🔄",
    rule: "Deload Every 5th Week",
    detail: "Drop all weights to 60% for one full week. Same exercises, same reps, half the load.",
  },
  {
    icon: "🛌",
    rule: "Fatigue Auto-Regulation",
    detail: "Sleep < 6 hrs or feeling run down? Drop volume by 1 set per exercise that day.",
  },
];

export function getTodayWorkout(): WorkoutDay {
  const dayIndex = new Date().getDay();
  return WORKOUT_DAYS.find((d) => d.dayIndex === dayIndex) || WORKOUT_DAYS[6];
}

export function getWorkoutByKey(key: string): WorkoutDay | undefined {
  return WORKOUT_DAYS.find((d) => d.key === key);
}
